gobstones/gobstones-web

app/elements/boards-panel/boards-panel.html, app/elements/gobstones-editor/gobstones-editor.html
=> Mover cabezal y booms

app/elements/editor-toolbar/editor-toolbar.html, app/elements/left-menu-code/left-menu-code.html, app/locales.json, app/scripts/behaviors/leftMenuBehavior.html
=> Feature project name on toolbar

app/elements/left-menu-code/left-menu-code.html, app/elements/main-app/main-app.html, app/styles/main.css
=>  Improved UI for left drawer

app/elements/gobstones-blockly/gobstones-blockly.html, bower.json
=> Bug primitive procedures

app/elements/gobstones-blockly/gobstones-blockly.html
=> Feature ignore aux declarations

app/electron-runner.js
The manu solves a MacOS issue as well as provides
feature for easier development and editor manipulation.
=> Added minimal menu that allows copy & paste

app/elements/attire-editor/attire-editor.html
=> Fix for issue: #380

package.json
Move version to update in production.
=> Update version to 2.17.1

app/elements/blocks-toolbox-selector/blocks-toolbox-selector.html, app/elements/boards-panel/boards-panel.html, app/elements/code-runner/code-runner.html, app/elements/metadata-editor/metadata-editor.html
Closes #412 
Obviamente, este botón solo se ve en modo Teacher, no aparece ni en Junior ni en Senior.
=> Boton previsualizar

app/elements/blocks-toolbox-selector/blocks-toolbox-selector.html, app/elements/gobstones-teacher/gobstones-teacher.html, app/elements/metadata-editor/metadata-editor.html, app/elements/metadata-editor/project-feature.html, app/scripts/features/project.html, app/scripts/loaders/components/metadataTeacherLoader.html
Closes #415 
Creé el **modo básico** de edición, que permite aplicar bloques de configuraciones de una vez. 
La configuración del modo seleccionado se guarda en una nueva clave `activity` dentro de `meta.yaml`.
=> Configuracion simplificada

app/elements/gobstones-blockly/gobstones-blockly.html, app/elements/gobstones-editor/gobstones-editor.html, app/elements/gobstones-teacher/alert-banner.html, app/elements/gobstones-teacher/gobstones-teacher.html, app/elements/metadata-editor/metadata-editor.html
Closes #401
Reordené las pestañas para que aparezca la bilbioteca del docente primera, como para alentar a que comiencen por ahí. 
El mensaje cambia a advertencia la primera vez que edita la solución del estudiante (código o bloques).
Editando bloques
Editando código
=> Aviso bloques desincronizados

app/elements/attire-editor/attire-editor.html
Closes #408 
* Agregué validación para cada elemento, se subraya en rojo si es erróneo.
* Agregué ícono y contador de caracteres restantes para texto.
* Reduje a 2 el máximo de caracteres que se pueden poner en una vestimenta.
=> Reglas vestimenta incompletas

app/elements/description-editor/description-editor.html
=> Tablero de ejemplo más representativo

app/elements/code-runner/code-runner.html
Closes #450 
Lo hice sin localización porque no me estaba funcionando. 🤷🏽
=> El tooltip "Ver como estudiante" cambia

app/elements/left-menu/left-menu.html
=> Ocultado código generado en modo texto

app/elements/gobstones-teacher/gobstones-teacher.html
Closes #468 
Closes #443 
Lindo hack sobre hack, freno la ejecución después de dispararla. :smiley:
=> Se frena la ejecución al correr el linter

bower.json
Closes #445  
El arreglo se hizo en el componente [gs-element-blockly](https://github.com/gobstones/gs-element-blockly/commit/446d4285753cf81994932ac81b1ad9ce5894ada6).
=> Corregida opción "Paso a paso" en menú contextual procedimientos

app/scripts/loaders/remote/gitHubLoader.html
Closes #478 
Hay que arreglar lo del SSL, lo pongo en otra issue para que no se nos olvide.
=> Se usa temporalmente activity en Heroku

app/elements/left-menu/left-menu.html, gulpfile.js, package.json, yarn.lock
Closes #481 
El arreglo se hizo principalmente en el componente  [left-menu](https://github.com/gobstones/gobstones-web/blob/ca8e0aa150ffc6eab807349f96500193608e4869/app/elements/left-menu/left-menu.html)
=> Se muestra la opción Código Generado en Gobstones Jr

app/scripts/loaders/remote/gitHubLoader.html
Reverts gobstones/gobstones-web#479
Closes #480
Esto volvería a usar nuevamente el server de la fundación.
=> Revert "Se usa temporalmente activity en Heroku"
